global:
  scrape_interval: 5s
  evaluation_interval: 2s
scrape_configs:
  - job_name: 'producer-service'
    static_configs:
      - targets: ['producer:50011']

  - job_name: 'consumer-service'
    static_configs:
      - targets: ['consumer:50022']